// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsDJpJrqxLBpqTJiGrJsUS1syPWKT4XR4',
    appId: '1:214867643271:web:98406904889a8dd9a1a122',
    messagingSenderId: '214867643271',
    projectId: 'mytest02-7109f',
    authDomain: 'mytest02-7109f.firebaseapp.com',
    storageBucket: 'mytest02-7109f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGZXoH2J-VY7TIKfejvb0gcxwEEsUfaGY',
    appId: '1:214867643271:android:81cc4ca06b9bbd97a1a122',
    messagingSenderId: '214867643271',
    projectId: 'mytest02-7109f',
    storageBucket: 'mytest02-7109f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2lkqULh-pEa-pBuuP8gxX9jMwDYiNfHk',
    appId: '1:214867643271:ios:42b63a78a15dc175a1a122',
    messagingSenderId: '214867643271',
    projectId: 'mytest02-7109f',
    storageBucket: 'mytest02-7109f.firebasestorage.app',
    iosBundleId: 'com.example.csefamily',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2lkqULh-pEa-pBuuP8gxX9jMwDYiNfHk',
    appId: '1:214867643271:ios:42b63a78a15dc175a1a122',
    messagingSenderId: '214867643271',
    projectId: 'mytest02-7109f',
    storageBucket: 'mytest02-7109f.firebasestorage.app',
    iosBundleId: 'com.example.csefamily',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsDJpJrqxLBpqTJiGrJsUS1syPWKT4XR4',
    appId: '1:214867643271:web:a0dd8e1308383190a1a122',
    messagingSenderId: '214867643271',
    projectId: 'mytest02-7109f',
    authDomain: 'mytest02-7109f.firebaseapp.com',
    storageBucket: 'mytest02-7109f.firebasestorage.app',
  );
}
